#!/bin/zsh

pxml=( output/packrat-*-xml.csv(om[1]) )
pjson=( output/packrat-*-json.csv(om[1]) )
dxml=( output/deriv-*-xml.csv(om[1]) )
djson=( output/deriv-*-json.csv(om[1]) )

gnuplot -e "pxml='${pxml}'; pjson='${pjson}'; dxml='${dxml}'; djson='${djson}'" plots.plg
