#!/bin/zsh

oxml=( output/naive-*-xml.csv(om[1]) )
ojson=( output/naive-*-json.csv(om[1]) )
nxml=( output/unaive-*-xml.csv(om[1]) )
njson=( output/unaive-*-json.csv(om[1]) )

if [[ ! -d plots ]]; then mkdir plots; fi

gnuplot -e "oxml='${oxml}'; ojson='${ojson}'; nxml='${nxml}'; njson='${njson}'" diff_plots.plg
