#!/bin/zsh

outname="output/deriv-`date +%y%m%d%H%M`-`git describe --tags --long`"

outfile="${outname}-xml.csv"
echo '"filename","output","user(s)","sys(s)","wall(s)","max-mem(KB)","size(B)"' | tee $outfile
# Iterate XML files sorted increasing by size
for file in input/ijs-elan2.0/*(oL[1,10]); do
	echo -n "\"`basename $file`\",\"" | tee -a $outfile
	/usr/bin/time -f "\",%U,%S,%e,%M," ../egg match XML.egg Document < $file 2>&1 | tr -d '\n' | tee -a $outfile
	stat -c %s $file | tee -a $outfile
done

echo

outfile="${outname}-json.csv"
echo '"filename","output","user(s)","sys(s)","wall(s)","max-mem(KB)","size(B)"' | tee $outfile
# Iterate JSON files sorted increasing by size
for file in input/json-ijs-elan2.0/*(oL[1,10]); do
	echo -n "\"`basename $file`\",\"" | tee -a $outfile
	/usr/bin/time -f "\",%U,%S,%e,%M," ../egg match JSON.egg JSON < $file 2>&1 | tr -d '\n' | tee -a $outfile
	stat -c %s $file | tee -a $outfile
done

# echo
# 
# outfile="${outname}-java.csv"
# echo '"filename","output","user(s)","sys(s)","wall(s)","max-mem(KB)","size(B)"' | tee $outfile
# # Iterate Java files sorted increasing by size
# for file in input/javacc/*(oL); do
# 	echo -n "\"`basename $file`\",\"" | tee -a $outfile
# 	/usr/bin/time -f "\",%U,%S,%e,%M," ../egg match Java.egg CompilationUnit < $file 2>&1 | tr -d '\n' | tee -a $outfile
# 	stat -c %s $file | tee -a $outfile
# done
