#!/bin/zsh

vertag="`date +%y%m%d%H%M`-`git describe --tags --long`"
outfile="output/deriv-${vertag}-exp.csv"

echo '"n","output","user(s)","sys(s)","wall(s)","max-mem(KB)"' | tee $outfile
# Iterate exponential files sorted increasing by size through derivative parser
for file in input/exp/*(oL[1,49]); do
	echo -n "`basename $file`,\"" | tee -a $outfile
	timeout 60s /usr/bin/time -f "\",%U,%S,%e,%M," ../egg match Exp.egg S < $file 2>&1 | tr -d '\n' | tee -a $outfile
	echo | tee -a $outfile
done

echo

outfile="output/packrat-${vertag}-exp.csv"

echo '"n","output","user(s)","sys(s)","wall(s)","max-mem(KB)"' | tee $outfile
# Iterate exponential files sorted increasing by size through derivative parser
for file in input/exp/*(oL); do
	echo -n "`basename $file`,\"" | tee -a $outfile
	timeout 60s /usr/bin/time -f "\",%U,%S,%e,%M," ../grammars/exp < $file 2>&1 | tr -d '\n' | tee -a $outfile
	echo | tee -a $outfile
done

echo

outfile="output/naive-${vertag}-exp.csv"

echo '"n","output","user(s)","sys(s)","wall(s)","max-mem(KB)"' | tee $outfile
# Iterate exponential files sorted increasing by size through derivative parser
for file in input/exp/*(oL[1,16]); do
	echo -n "`basename $file`,\"" | tee -a $outfile
	timeout 60s /usr/bin/time -f "\",%U,%S,%e,%M," ../grammars/exp-nomemo < $file 2>&1 | tr -d '\n' | tee -a $outfile
	echo | tee -a $outfile
done
